Add code block environment in myst-to-tex
executablebooks/mystjs pull request #393
Opened 2023-05-20 18:29 UTC by finsberg

2023-05-30 17:08 UTC, rowanc1 requested changes
@finsberg this looks great, and is a good way to unblock your use case!

I think that we should still likely consider this or `listings` to be the default code environment in a future PR, as well as having this configuration from the `myst.yml` or frontmatter as well. Both of those changes are complimentary to this though, and we can adapt to any changes relatively easily.

The only change I would request is allowing the class attribute to be a CSS-style string with a list of class names. I added a bit of code from the `myst-theme` that could be used here.

Let me know if you are up for making that improvement, or I can jump in and help.

Thanks for the PR! 🚀

2023-05-30 17:08 UTC, rowanc1 commented on packages/myst-to-tex/src/index.ts
> +    if (node.class === 'minted' && node.lang !== undefined) {
I think the only improvements I would suggest to this is that the class might be a space-separated (i.e. css) string.

Something similar to:

```typescript
function getClasses(className?: string): string[] {
  const classes =
    className
      ?.split(' ')
      .map((s) => s.trim().toLowerCase())
      .filter((s) => !!s) ?? [];
  return [...new Set(classes)];
}
```

and then a `getClasses(node.class).includes('minted')` should work well for this use case I think.

2023-05-30 17:08 UTC, rowanc1 commented on packages/myst-to-tex/tests/basic.yml
> +          class: minted
We could update the test a tiny bit here just to add a new class name:

```suggestion
          class: some-class minted
```

2023-06-05 07:04 UTC, finsberg commented
@rowanc1 Thanks for your input. I think this is a good idea. I have changed the PR according to your suggestions.

Let me know if it looks good or if you want additional changes. I also added an option to use `listings` instead of `minted` using en `if-else if` clause. 

I can also give it a try to create a new PR for adding the configuration to the `myst.yml` or frontmatter if this is of interest?

2023-06-07 17:06 UTC, merged

2023-06-07 17:10 UTC, rowanc1 commented
Thanks @finsberg for the PR -- happy to have another one targeting the `myst.yml`.

We don't currently have anything like that (config options that make it to the writers), so there might be some poking around/discussion to be had (I know that @fwkoch has thoughts there!).

Let me know if you are up for it and we can put together a bit of a roadmap for the feature and try to think through where some of the hard parts are!

I will plan to release this class-based highlighting in the next few days.

2023-06-07 19:24 UTC, finsberg commented
> Thanks @finsberg for the PR -- happy to have another one targeting the `myst.yml`.
> 
> We don't currently have anything like that (config options that make it to the writers), so there might be some poking around/discussion to be had (I know that @fwkoch has thoughts there!).
> 
> Let me know if you are up for it and we can put together a bit of a roadmap for the feature and try to think through where some of the hard parts are!
> 
> I will plan to release this class-based highlighting in the next few days.

@rowanc1  Sounds great! I would definitely like to contribute to a feature like that. I really like this project and I think it has a great potential to change the way we write academic papers. I will also start adopting mystjs for my future academic papers and will try to contribute the best I can in order to push this project forward. Thanks again for a great project.

2023-06-08 17:55 UTC, rowanc1 commented
This is released in v`0.1.31`! Coming to a live demo near you soon 🚀 

![code-latex-class](https://github.com/executablebooks/mystjs/assets/913249/bcf23f9c-272f-4aed-9ae6-9c3cba5d7efb)

Thanks for the kind words, really excited about MyST, I think it can change a lot of things in science communication!